theme: jekyll-theme-cayman

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions

title: Elegant
markdown: kramdown
highlighter: rouge
author:
  name:       Gaurav Panchal
  url:        http://grvpanchal.ml/elegant